name: CI - Chatty

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  #build:

  #  runs-on: ubuntu-latest

  #  steps:
  #  - name: Checkout code
  #    uses: actions/checkout@v4

  #  - name: Setup Node.js environment
  #    uses: actions/setup-node@v6.0.0
  #    with:
  #      node-version: 18
  #      cache: npm

  #  - name: Dependencies
  #    run: npm install

  #  - name: Build docker image
  #    run: docker build -t chatty .

  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/main'

  #   steps:
  #     - name: Deploy to render
  #       run: |
  #         curl -X POST \
  #           -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
  #           -H "Content-Type: application/json" \
  #           https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys